class SaleItem {
  final int id;
  final int medicine;
  final int batch;
  final int quantity;
  final double unitPrice;
  final double subtotal;

  const SaleItem({
    required this.id,
    required this.medicine,
    required this.batch,
    required this.quantity,
    required this.unitPrice,
    required this.subtotal,
  });

  factory SaleItem.fromJson(Map<String, dynamic> json) {
    return SaleItem(
      id: json['id'] ?? 0,
      medicine: json['medicine'] ?? 0,
      batch: json['batch'] ?? 0,
      quantity: json['quantity'] ?? 0,
      unitPrice:
          double.tryParse(json['unit_price'].toString()) ?? 0.0,
      subtotal:
          double.tryParse(json['subtotal'].toString()) ?? 0.0,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      // id and subtotal are generated by the backend
      'medicine': medicine,
      'batch': batch,
      'quantity': quantity,
      'unit_price': unitPrice,
    };
  }
}